version: "3.9"

services:
  shipments-svc-s12:
    build: ./shipments_service
    container_name: shipments-svc-s12
    ports:
      - "8130:8130"
    command: uvicorn app:app --host 0.0.0.0 --port 8130

  other-svc:
    build: ./other_service
    container_name: other-svc
    ports:
      - "8172:8172"
    command: uvicorn app:app --host 0.0.0.0 --port 8172

  nginx:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./weeks/week-03/infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shipments-svc-s12
      - other-svc