events {}

http {
    upstream shipments-svc-s12 {
        server shipments-svc-s12:8130;
    }

    upstream other-svc {
        server other-svc:8172;
    }

    server {
        listen 80;

        location /api/shipments {
            proxy_pass http://shipments-svc-s12/shipments;
        }

        location /api/other {
            proxy_pass http://other-svc/other;
        }
    }
}
